# A workflow that builds & tests the package on all supported platforms

name: Test

on:
  pull_request:
    branches: ['**']

  workflow_dispatch:

jobs:
  test-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: swift test

  test-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          swift-version: "5.5"

  test-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Test macOS
        run: swift test

  test-ios:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Test iOS
        run: xcodebuild test -scheme swift-cuckoo-collections -destination "platform=iOS Simulator,name=iPhone 12,OS=15.0"

  test-watchos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Test watchOS
        run: xcodebuild test -scheme swift-cuckoo-collections -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=8.0"

  test-tvos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Test tvOS
        run: xcodebuild test -scheme swift-cuckoo-collections -destination "platform=tvOS Simulator,name=Apple TV 4K,OS=15.0"
